# Generated by Django 2.2.6 on 2019-11-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_coinpayments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coin_payment_status',
            field=models.CharField(default='Waiting for buyer', max_length=4),
        ),
    ]
