# Generated by Django 2.2.6 on 2019-11-14 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_coinpayments', '0002_payment_coin_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinWithdrawalTransaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('send_address', models.CharField(max_length=150, verbose_name='Send Address')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=65, verbose_name='Amount')),
                ('coin', models.CharField(max_length=20, verbose_name='Coin')),
            ],
            options={
                'verbose_name': 'Withdrawal Transaction',
                'verbose_name_plural': 'Withdrawals Transactions',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('BCH', 'Bitcoin Cash'), ('BTC', 'Bitcoin'), ('DASH', 'Dash'), ('ETH', 'Ether'), ('USD', 'USD')], max_length=8, verbose_name='Withdrawal currency')),
                ('currency2', models.CharField(choices=[('BCH', 'Bitcoin Cash'), ('BTC', 'Bitcoin'), ('DASH', 'Dash'), ('ETH', 'Ether'), ('USD', 'USD')], default='USD', max_length=8, verbose_name='Exchange currency')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('CANCEL', 'Cancelled'), ('WAIT', 'Waiting for email confirmation'), ('PEND', 'Pending'), ('COMPL', 'Completed')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=65, verbose_name='Amount')),
                ('send_address', models.CharField(max_length=150, verbose_name='Send Address')),
                ('auto_confirm', models.BooleanField(default=False, verbose_name='Auto Confirm')),
                ('add_tx_fee', models.BooleanField(default=True, verbose_name='Add Transaction Fee')),
                ('provider_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_coinpayments.CoinWithdrawalTransaction', verbose_name='Withdrawal transaction')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
            },
        ),
    ]
